# Generated by Django 6.0.3 on 2026-03-04 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la partie')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('objective', models.TextField(blank=True, verbose_name='Objectif pédagogique')),
                ('prerequisites', models.TextField(blank=True, verbose_name='Prérequis')),
                ('estimated_duration', models.CharField(blank=True, max_length=64, verbose_name='Durée estimée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='courses.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Partie',
                'verbose_name_plural': 'Parties',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('title', 'Titre'), ('paragraph', 'Paragraphe'), ('objective', 'Objectif pédagogique'), ('list', 'Liste'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Vidéo'), ('qcu', 'Question à une seule bonne réponse'), ('qcm', 'Question à plusieurs bonnes réponses'), ('ordering', "Mettre dans l'ordre"), ('numeric', 'Réponse numérique'), ('fill_blank', 'Texte à compléter'), ('categorize', 'Catégoriser')], max_length=32, verbose_name='Type de bloc')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='Contenu')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('objective', models.TextField(blank=True, verbose_name='Objectif')),
                ('estimated_duration', models.CharField(blank=True, max_length=64, verbose_name='Durée estimée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='courses.part', verbose_name='Partie')),
            ],
            options={
                'verbose_name': 'Bloc',
                'verbose_name_plural': 'Blocs',
                'ordering': ['position', 'id'],
            },
        ),
    ]
